#!/usr/bin/perl
#Script Name: howLong.pl
#Author: Nathan Handler <nhandler@ubuntu.com>

use strict;
use warnings;
use Date::Manip;

my $target=$ARGV[0] || "Tue, 14 Jul 2015 11:49:57 UTC";
my $delta = DateCalc(ParseDate("today"),ParseDate($target),1);

$delta=~s/^[+-]//;
my($y,$m,$w,$d,$h,$min,$s) = split(/:/,$delta,7);

print $y . "y " if($y>0);
print $m . "m " if($m>0);
print $w . "w " if($w>0);
print $d . "d " if($d>0);
print "$h:$min:$s" if($h>0||$min>0||$s>0);