#!/bin/bash

QDBUS="qdbus org.mpris.amarok"
TRACK=`$QDBUS /TrackList org.freedesktop.MediaPlayer.GetCurrentTrack`
LEN=$2

case "$1" in

# Now Playing Info
artist) ARTIST=`qdbus org.mpris.amarok /TrackList org.freedesktop.MediaPlayer.GetMetadata $TRACK | sort -r | egrep "^(artist:)" | sed -e "s/^.*: //g"`
if [ ${#ARTIST} -gt $LEN ]; then 
    echo $ARTIST | head -c $[$LEN-3] 
    echo "..."
else 
    echo $ARTIST
fi
;;

title) TITLE=`qdbus org.mpris.amarok /TrackList org.freedesktop.MediaPlayer.GetMetadata $TRACK | sort -r | egrep "^(title:)" | sed -e "s/^.*: //g"`
if [ ${#TITLE} -gt $LEN ]; then 
    echo $TITLE | head -c $[$LEN-3] 
    echo "..."
else 
    echo $TITLE
fi
;;

album) ALBUM=`qdbus org.mpris.amarok /TrackList org.freedesktop.MediaPlayer.GetMetadata $TRACK | sort -r | egrep "^(album:)" | sed -e "s/^.*: //g"`
if [ ${#ALBUM} -gt $LEN ]; then 
    echo $ALBUM | head -c $[$LEN-3] 
    echo "..."
else 
    echo $ALBUM
fi
;;

esac